version: "3"
services:
  microblog:
    image: microblog
    build: ./
    container_name: "microblog"
    restart: "unless-stopped"
    ports:
      - 5000:5000
    environment:
      - TESTING=${TESTING:-false}
